services:
  - type: web
    name: phisheye-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir BackEnd --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12 # Matches current development environment
